// Build-time loader for the Delivery view (S14-SR-07): exposes the committed
// dora.json (DORA metrics computed from git) to the docs site. Nothing here
// recomputes — the metrics are generated by scripts/dora-metrics.mjs.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineLoader } from 'vitepress'

export interface DoraRelease {
  tag: string
  date: string
  commits: number
  intervalDays: number | null
  leadTimeDays: number | null
  isPatch: boolean
  failure: boolean
  restoreDays: number | null
}

export interface DoraData {
  generatedAt: string
  releaseCount: number
  firstRelease: string | null
  lastRelease: string | null
  metrics: {
    deploymentFrequency: { medianIntervalDays: number | null; perWeek: number | null; band: string }
    leadTimeForChanges: { medianDays: number | null; band: string }
    changeFailureRate: { percent: number | null; failures: number; of: number; band: string }
    timeToRestore: { medianDays: number | null; failures: number; band: string }
  }
  perRelease: DoraRelease[]
}

declare const data: DoraData
export { data }

const DORA_PATH = resolve(__dirname, '../../dora.json')

export default defineLoader({
  watch: [DORA_PATH],
  load: (): DoraData => JSON.parse(readFileSync(DORA_PATH, 'utf-8')) as DoraData,
})
