// Publish the mutation score (S18): turn Stryker's JSON report into a small,
// committed, per-file artifact other tools can read without re-running a
// mutation run.
//
// Usage:
//   node scripts/mutation-score.mjs           write mutation-score.json
//   node scripts/mutation-score.mjs --check   verify the committed file matches
//                                             the current report (exit 1 on drift)
//
// This script is the machine-readable authority for the score formula
// (S18-SR-02); specs/S18-mutation-score.md mirrors it in prose. It is NOT part
// of `npm run verify` — a full mutation run is orders of magnitude slower than
// the rest of the gate (S18-SR-04).
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname, relative, isAbsolute } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REPORT_PATH = join(ROOT, 'reports', 'mutation', 'mutation.json');
const OUT_PATH = join(ROOT, 'mutation-score.json');

/** Mutant statuses that count as "the tests caught it". */
export const KILLED_STATUSES = ['Killed', 'Timeout'];
/** Statuses that count against the score — a mutant the tests let through. */
export const SURVIVED_STATUSES = ['Survived', 'NoCoverage'];
/** Statuses excluded from the denominator entirely: they say nothing about
 *  test strength, only that the mutant could not be evaluated. */
export const IGNORED_STATUSES = ['CompileError', 'RuntimeError', 'Ignored'];

/** The mutation-testing standard score (S18-SR-02):
 *  (killed + timeout) / (killed + timeout + survived + noCoverage). */
export function scoreOf(tallies) {
  const detected = KILLED_STATUSES.reduce((n, s) => n + (tallies[s] ?? 0), 0);
  const undetected = SURVIVED_STATUSES.reduce((n, s) => n + (tallies[s] ?? 0), 0);
  const total = detected + undetected;
  return total === 0 ? null : Math.round((detected / total) * 1000) / 10;
}

/** Read Stryker's JSON report and reduce it to per-file tallies + scores. */
export function computeMutationScore(reportPath = REPORT_PATH, rootDir = ROOT) {
  const report = JSON.parse(readFileSync(reportPath, 'utf-8'));
  const files = {};
  const overall = {};
  for (const [path, entry] of Object.entries(report.files ?? {})) {
    // The artifact stores repo-relative POSIX paths so the docs loader can
    // join them to the matrix's impl[] entries. Stryker has reported both
    // absolute and already-relative keys across versions, and calling
    // relative() on an already-relative key would resolve it against cwd and
    // mangle it — so only rebase what is actually absolute.
    const rel = (isAbsolute(path) ? relative(rootDir, path) : path).split('\\').join('/');
    const tallies = {};
    for (const m of entry.mutants ?? []) {
      tallies[m.status] = (tallies[m.status] ?? 0) + 1;
      overall[m.status] = (overall[m.status] ?? 0) + 1;
    }
    const mutants = Object.values(tallies).reduce((a, b) => a + b, 0);
    // A file Stryker did not mutate is absent from the report and therefore
    // absent here too (S18-SR-05) — never present with a zero.
    if (mutants === 0) continue;
    files[rel] = { mutants, tallies, score: scoreOf(tallies) };
  }
  const sorted = Object.fromEntries(Object.keys(files).sort().map((k) => [k, files[k]]));
  const stryker = JSON.parse(readFileSync(join(rootDir, 'stryker.config.json'), 'utf-8'));
  return {
    $comment:
      'Mutation score per source file (S18), generated by scripts/mutation-score.mjs ' +
      'from Stryker\'s JSON report — do not edit by hand. Run `npm run test:mutation` ' +
      'then `npm run mutation:score` to refresh. NEVER read by the maturity scorer.',
    generatedAt: new Date().toISOString().slice(0, 10),
    breakThreshold: stryker.thresholds?.break ?? null,
    overall: {
      mutants: Object.values(overall).reduce((a, b) => a + b, 0),
      tallies: overall,
      score: scoreOf(overall),
    },
    files: sorted,
  };
}

// ── CLI ─────────────────────────────────────────────────────────────────────

const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop());
if (isMain) {
  if (!existsSync(REPORT_PATH)) {
    console.error(`No Stryker report at ${relative(ROOT, REPORT_PATH)} — run \`npm run test:mutation\` first.`);
    process.exit(1);
  }
  const next = computeMutationScore();
  const check = process.argv.includes('--check');
  if (check) {
    if (!existsSync(OUT_PATH)) {
      console.error('mutation-score.json is missing — run `npm run mutation:score`.');
      process.exit(1);
    }
    // generatedAt moves on every run; the scores are what must not drift.
    const committed = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));
    const strip = (o) => JSON.stringify({ overall: o.overall, files: o.files });
    if (strip(committed) !== strip(next)) {
      console.error('mutation-score.json is stale — run `npm run mutation:score`.');
      process.exit(1);
    }
    console.log(`✓ mutation-score.json matches the current report (${next.overall.score}%).`);
  } else {
    writeFileSync(OUT_PATH, JSON.stringify(next, null, 2) + '\n');
    const n = Object.keys(next.files).length;
    console.log(`Mutation score: ${next.overall.score}% across ${n} file(s), ${next.overall.mutants} mutants.`);
    console.log(`Wrote ${relative(ROOT, OUT_PATH)}.`);
  }
}
